adam_kwargs:
  lr: 0.0001
batch_sizes:
  128: 64
checkpoint_root: ./output/checkpoint/brain/pixel/axis_0
dec:
  kwargs:
    inner_dims:
    - 128
    - 128
    - 128
    - 128
    - 128
    - 128
    - 128
  type: residual9
early_stopping_min_delta: 0.002
early_stopping_patience: 3
enc:
  kwargs:
    inner_dims:
    - 128
    - 128
    - 128
    - 128
    - 128
    - 128
    - 128
  type: residual9
finetune_from: null
image_dim: 1
image_rec_loss:
  loss_kwargs:
    normalize_to_vgg_input: false
    path_to_vgg19_weights: ./output/vgg_weights/simclr_exp_1.tar
    use_smooth_pg: false
    weights_per_resolution:
      128:
        feature_weights:
          r32: 1
        img_weight: 0
  loss_type: relative_perceptual_L1
image_sample_iter: 1000
initial_image_res: 128
iters_per_res: {}
latent_dim: 128
latent_res: 1
log_iter: 10
log_root: ./output/logs/brain/pixel/axis_0
max_image_res: 128
model_type: dpa
num_workers: 16
random_seed: 5317
stab_iter: 300000
train_dataset:
  dataset_kwargs:
    cache: false
    fold: 0
    folds_path: ./folds/brain/train_folds_10.csv
    image_root: ./data/preprocessed/brain_train/2d_axis_0
    split: train
  dataset_type: numpy2d
  transform_kwargs:
    resize: 128
trns_iter: 0
val_dataset:
  dataset_kwargs:
    cache: false
    fold: 0
    folds_path: ./folds/brain/train_folds_10.csv
    image_root: ./data/preprocessed/brain_train/2d_axis_0
    split: val
  dataset_type: numpy2d
  transform_kwargs:
    resize: 128
val_iter: 10000
verbose: true
