apply_along_axis: 1
delete_zero_area: false
do_not_process_small_area: true

model_type: dpa
results_root: # PUT PATH TO SAVE MODEL INFERENCE AND RESULTS
save_inference: false
score_reduction: max
test_dataset:
  dataset_kwargs:
    fold: 0
    folds_path: # PUT PATH TO FOLDS HERE
    image_root: # PUT IMAGE_ROOT TO GENERATED 3D VOLUMES WITH ANOMALIES HERE
    mask_root: # PUT ROOT TO GENERATED MASKS OF 3D VOLUMES WITH ANOMALIES HERE
    split: val
  dataset_type: nifti3d
  transform_kwargs:
    resize: 128
test_image_rec_loss:
  loss_kwargs:
    mode_3d: true
    normalize_to_vgg_input: false
    path_to_vgg19_weights: # PUT PATH TO TRAINED VGG19 WEIGHTS HERE
    use_smooth_pg: false
    weights_per_resolution:
      128:
        feature_weights:
          r42: 1
        img_weight: 0
  loss_type: relative_perceptual_L1
test_model_path: # PUT {checkpoint_root}/anomaly_detection.tar
resize_3d_for_evaluation: 128
verbose: true
