##=========================== CONFIG FOR INFERENCE ===========================

model_type: dpa

verbose: True
save_inference: False


apply_along_axis: 0
score_reduction: max
do_not_process_small_area: True
delete_zero_area: False
resize_3d_for_evaluation: 128


test_dataset:
  dataset_type: nifti3d
  dataset_kwargs:
    image_root: ./data/preprocessed/brain_train/3d_test
    mask_root: data/preprocessed/brain_train/3d_test_masks
    folds_path: ./folds/brain/train_folds_10.csv
    fold: 0
    split: val
  transform_kwargs:
    resize: 64

test_image_rec_loss:
  loss_type: relative_perceptual_L1
  loss_kwargs:
    mode_3d: True
    path_to_vgg19_weights: ./output/vgg_weights/simclr_exp_1.tar
    normalize_to_vgg_input: False
      64:
        img_weight: 0
        feature_weights:
          r42: 1
    use_smooth_pg: False



results_root: ./output/results/example
test_model_path: ./output/checkpoint/example/anomaly_detection.tar
