do_not_process_small_area: True
delete_zero_area: False
resize: 128

path_to_vgg19_weights: /workspace/data/vgg_weights/simclr_exp_1.tar

models:
  - checkpoint_path: /workspace/data/abdom/sample/axis_0/anomaly_detection.tar
    along_axis: 0
    resize: 128

  - checkpoint_path: /workspace/data/abdom/sample/axis_2/anomaly_detection.tar
    along_axis: 2
    resize: 128
